kind: Service
apiVersion: v1
metadata:
  name: movie-store
spec:
  selector:
    app: movie-store
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  selector:
      matchLabels:
        app: movie-store
  replicas: 3
  template:
    metadata:
      labels:
        app: movie-store
    spec:
      containers:
        - name: movie-store
          image: movie-store:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: movie-db-config  
                  key: database
            - name: SPRING_DATA_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: movie-db-config 
                  key: host
            - name: SPRING_DATA_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: movie-db-config
                  key: port

